-- Creating CATEGORY table
CREATE TABLE CATEGORY (
    category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE
);

-- Creating PRODUCT table
CREATE TABLE PRODUCT (
    product_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    quantity NUMBER DEFAULT 0 NOT NULL,
    category_id NUMBER,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id)
);

-- Creating CUSTOMER table
CREATE TABLE CUSTOMER (
    customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20) UNIQUE
);

-- Creating SUPPLIER table
CREATE TABLE SUPPLIER (
    supplier_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    contact VARCHAR2(100)
);

-- Creating EMPLOYEE table
CREATE TABLE EMPLOYEE (
    employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    role VARCHAR2(50),
    phone VARCHAR2(20) UNIQUE
);

-- Creating INVOICE table
CREATE TABLE INVOICE (
    invoice_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    employee_id NUMBER,
    invoice_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_invoice_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
    CONSTRAINT fk_invoice_employee FOREIGN KEY (employee_id) REFERENCES EMPLOYEE(employee_id)
);

-- Creating INVOICE_DETAIL table
CREATE TABLE INVOICE_DETAIL (
    invoice_detail_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    invoice_id NUMBER,
    product_id NUMBER,
    quantity NUMBER NOT NULL,
    CONSTRAINT fk_invoice_detail_invoice FOREIGN KEY (invoice_id) REFERENCES INVOICE(invoice_id),
    CONSTRAINT fk_invoice_detail_product FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id)
);

-- Creating ORDER_SUPERMARKET table
CREATE TABLE ORDER_SUPERMARKET (
    order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    supplier_id NUMBER,
    quantity NUMBER NOT NULL,
    order_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_order_product FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id),
    CONSTRAINT fk_order_supplier FOREIGN KEY (supplier_id) REFERENCES SUPPLIER(supplier_id)
);

-- Creating STOCK table
CREATE TABLE STOCK (
    stock_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_id NUMBER UNIQUE,
    quantity NUMBER DEFAULT 0 NOT NULL,
    last_updated TIMESTAMP DEFAULT SYSTIMESTAMP, -- Removed ON UPDATE CURRENT_TIMESTAMP
    CONSTRAINT fk_stock_product FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id)
);

-- Creating AUDIT_LOG table
CREATE TABLE AUDIT_LOG (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    action VARCHAR2(255) NOT NULL,
    user_id NUMBER,
    log_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP
    -- You might add a foreign key here if 'user_id' consistently refers to an ID in another table (e.g., EMPLOYEE)
    -- CONSTRAINT fk_audit_employee FOREIGN KEY (user_id) REFERENCES EMPLOYEE(employee_id)
);

-- Creating HOLIDAY table
CREATE TABLE HOLIDAY (
    holiday_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    holiday_date DATE NOT NULL UNIQUE
);
